### ISSUE TITLE
Explorer Witness Links Can Be Too Long

### ISSUE THREAD

**Issue by Kennybll** [GravityProtocol/gravity-core#1]
![image](https://user-images.githubusercontent.com/14302151/40563244-1e4cc288-6032-11e8-8ff9-e1ce19efea5a.png)
As you can see the link to my witness proposal is covered up by my supports voting weight. 
Suggestion to either truncate the url, or use the below image to link to the proposal like in https://wallet.gravityprotocol.org.
![image](https://user-images.githubusercontent.com/14302151/40563350-6ac9275a-6032-11e8-918c-fb028166fb44.png)

**Comment by pkosov** [comment]
This bug is fixed.

Thank you.
