### ISSUE TITLE
[BUG] Account Search does not work

### ISSUE THREAD

**Issue by btsfav** [GravityProtocol/gravity-core#2]
System: Win7, Google Chrome latest release, lastpass activated

![image](https://user-images.githubusercontent.com/15261692/40623447-753b7284-62a7-11e8-87ce-59b4e3bf3e9a.png)

I'm able to type in a username, but nothing happens after.

**Comment by btsfav** [comment]
may be related, some obscure script is blocked by scriptsafe:

![image](https://user-images.githubusercontent.com/15261692/40623796-0c5fd334-62a9-11e8-9648-e3382414a60a.png)

**Comment by pkosov** [comment]
This bug is fixed.

Thank you.
